# Generated by Django 4.0.4 on 2022-05-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(default=1, max_length=222),
            preserve_default=False,
        ),
    ]
