# Generated by Django 4.0.4 on 2022-05-12 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0002_images_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('choice', models.CharField(choices=[(1, 'Python'), (2, 'Java')], max_length=255)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='dimension',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='images',
            name='format',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='images',
            name='license',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='images',
            name='view_image',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='media/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('view_image', models.IntegerField()),
                ('license', models.TextField(blank=True)),
                ('dimension', models.CharField(blank=True, max_length=255)),
                ('format', models.CharField(blank=True, max_length=255)),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp.tags')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='temp.tags'),
            preserve_default=False,
        ),
    ]
