# Generated by Django 4.0.4 on 2022-05-12 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0004_remove_images_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('image', models.FileField(upload_to='media/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('view_image', models.IntegerField()),
                ('license', models.TextField(blank=True)),
                ('dimension', models.CharField(blank=True, max_length=255)),
                ('format', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp.tag'),
        ),
    ]
