# Generated by Django 4.0.4 on 2022-05-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0005_image_rename_videos_video_delete_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='image',
            new_name='video',
        ),
    ]
