# Generated by Django 4.0.4 on 2022-05-23 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=200, unique=True)),
                ('file', models.FileField(blank=True, upload_to='media/')),
                ('content', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('Политика', 'Политика'), ('Спорт', 'Спорт'), ('Комедии', 'Комедии'), ('Музыка', 'Музыка'), ('Youtube', 'Youtube')], db_index=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
