# Generated by Django 4.0.4 on 2022-05-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(blank=True)),
                ('height', models.IntegerField(blank=True)),
                ('length', models.IntegerField(blank=True)),
                ('volume', models.IntegerField(blank=True)),
                ('weight', models.IntegerField(blank=True)),
                ('price', models.IntegerField(blank=True)),
            ],
        ),
    ]
