# Generated by Django 4.0.4 on 2022-05-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('salary', models.IntegerField(verbose_name='ЗП')),
                ('skill', models.CharField(max_length=255, verbose_name='Опыт')),
                ('image', models.ImageField(upload_to='image/%Y/%m/%d', verbose_name='Фото')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('public', models.DateTimeField(default=True, verbose_name='Опубликованно')),
            ],
        ),
    ]
